version: "3"

services:
  lark-es:
    image: elasticsearch:8.3.3
    container_name: lark-es
    restart: always
    ports:
      - 19200:9200
      - 19300:9300
    volumes:
      - /Volumes/data/lark/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - /Volumes/data/lark/elasticsearch/logs:/user/share/elasticsearch/logs:rw
      - /Volumes/data/lark/elasticsearch/plugins:/usr/share/elasticsearch/plugins:rw
    privileged: true
    environment:
      - discovery.type=single-node
      - node.name=lark-es-01
      - cluster.name=lark-es-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-headers="*"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "ELASTIC_PASSWORD=lart2022"